/* Automatically generated by wasm2c */
#ifndef CALCULATOR_C_H_GENERATED_
#define CALCULATOR_C_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct w2c_calculator {
  char dummy_member;
} w2c_calculator;

void wasm2c_calculator_instantiate(w2c_calculator*);
void wasm2c_calculator_free(w2c_calculator*);
wasm_rt_func_type_t wasm2c_calculator_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* export: 'soma' */
u32 w2c_calculator_soma(w2c_calculator*, u32, u32);

/* export: 'subtracao' */
u32 w2c_calculator_subtracao(w2c_calculator*, u32, u32);

/* export: 'divisao' */
u32 w2c_calculator_divisao(w2c_calculator*, u32, u32);

/* export: 'multiplicacao' */
u32 w2c_calculator_multiplicacao(w2c_calculator*, u32, u32);

#ifdef __cplusplus
}
#endif

#endif  /* CALCULATOR_C_H_GENERATED_ */
