link:
	rustc link.rs --target wasm32-unknown-unknown --crate-type=cdylib

runtime:
	rustc runtime.rs --target wasm32-unknown-unknown --crate-type=cdylib

exception:
	rustc exception.rs --target wasm32-unknown-unknown --crate-type=cdylib
